export interface ExploratoryTest {
  id: string;
  category: string;
  title: string;
  howToTest: string;
  pageUrl: string;
  pageLabel: string;
}

export interface ExploratoryTestCategory {
  key: string;
  label: string;
  priority: "ALTA" | "MÉDIA" | "BAIXA";
}

export const EXPLORATORY_TEST_CATEGORIES: ExploratoryTestCategory[] = [
  { key: "scanner", label: "Scanner de Código de Barras", priority: "ALTA" },
  { key: "rascunho", label: "Rascunho IndexedDB", priority: "ALTA" },
  { key: "inline-lote", label: "Produto Inline + Lote", priority: "ALTA" },
  { key: "transferencias", label: "Transferências", priority: "ALTA" },
  { key: "prompts", label: "Geração de Prompts com IA", priority: "MÉDIA" },
  { key: "produto-form", label: "Formulário de Produto", priority: "MÉDIA" },
  { key: "api", label: "API — Retry com Refresh de Token", priority: "MÉDIA" },
  { key: "toasts", label: "Toasts — Estilo + Traduções", priority: "BAIXA" },
  { key: "warehouse", label: "Warehouse — Hidratação Síncrona", priority: "BAIXA" },
];

export const EXPLORATORY_TESTS: ExploratoryTest[] = [
  // === Scanner ===
  {
    id: "scanner-scan-normal",
    category: "scanner",
    title: "Scan de produto existente",
    howToTest: "Vá para a página de criar movimentação. Clique no ícone de scanner. Aponte a câmera para um código de barras de um produto que já existe no sistema. O produto deve ser encontrado e adicionado.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  {
    id: "scanner-rescan-debounce",
    category: "scanner",
    title: "Mesmo código em menos de 1,5 segundos",
    howToTest: "Escaneie o mesmo código de barras duas vezes bem rápido (menos de 1,5s entre os scans). O segundo scan deve ser ignorado.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  {
    id: "scanner-permission-denied",
    category: "scanner",
    title: "Permissão de câmera negada",
    howToTest: "Abra o scanner. Quando o navegador pedir permissão da câmera, clique em 'Bloquear'. Deve aparecer um modal de erro com um botão 'Copiar Conteúdo'.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  {
    id: "scanner-no-camera",
    category: "scanner",
    title: "Dispositivo sem câmera",
    howToTest: "Em um computador sem webcam, tente abrir o scanner. Deve aparecer o modal de erro com as informações do erro em formato JSON.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  {
    id: "scanner-multi-camera",
    category: "scanner",
    title: "Rotação entre câmeras (múltiplas câmeras)",
    howToTest: "Em um celular ou tablet com câmera frontal e traseira, abra o scanner. O sistema deve alternar entre as câmeras automaticamente se uma falhar.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  {
    id: "scanner-ios-pwa",
    category: "scanner",
    title: "Scanner no PWA do iOS",
    howToTest: "Abra o aplicativo como PWA no iPhone/iPad (adicione à tela de início). Use o scanner. Deve funcionar com a câmera.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  {
    id: "scanner-inline-not-found",
    category: "scanner",
    title: "Produto inline — código não encontrado",
    howToTest: "Na página de criar movimentação, selecione um tipo de entrada (Compra ou Ajuste de Entrada). Escaneie um código de barras que não existe. Deve aparecer um modal perguntando se deseja criar o produto.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  // === Rascunho IndexedDB ===
  {
    id: "rascunho-reload",
    category: "rascunho",
    title: "Rascunho persiste ao recarregar a página",
    howToTest: "Na página de criar movimentação, preencha alguns campos (tipo, quantidade, adicione um produto). Aperte F5 para recarregar. Os dados devem voltar e um toast verde 'Rascunho da movimentação restaurado' deve aparecer.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  {
    id: "rascunho-close-tab",
    category: "rascunho",
    title: "Rascunho sobrevive ao fechar a aba",
    howToTest: "Preencha parte da movimentação. Feche a aba completamente. Abra uma nova aba e volte para a página de criar movimentação. O rascunho deve ser restaurado com o toast.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  {
    id: "rascunho-image-blob",
    category: "rascunho",
    title: "Imagem do produto inline preservada no rascunho",
    howToTest: "Adicione um produto inline com uma imagem. Recarregue a página (F5). A imagem deve continuar aparecendo no formulário.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  {
    id: "rascunho-two-tabs",
    category: "rascunho",
    title: "Duas abas simultâneas",
    howToTest: "Abra duas abas na mesma página de criar movimentação. Altere dados na primeira aba, depois na segunda. O sistema deve detectar conflito de versão.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  {
    id: "rascunho-anonimo",
    category: "rascunho",
    title: "IndexedDB indisponível (guia anônima)",
    howToTest: "Abra o aplicativo em uma janela anônima/privada. Preencha a movimentação e recarregue. Os dados serão perdidos (sem IndexedDB).",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  {
    id: "rascunho-warehouse-trocada",
    category: "rascunho",
    title: "Warehouse trocada entre sessões",
    howToTest: "Selecione o warehouse A. Crie um rascunho de movimentação. Troque para o warehouse B no menu superior. Recarregue a página. O rascunho NÃO deve ser restaurado.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  {
    id: "rascunho-submit-progress",
    category: "rascunho",
    title: "Barra de progresso ao finalizar",
    howToTest: "Crie uma movimentação com vários itens inline (com imagens). Clique em 'Finalizar'. Deve aparecer uma barra com os passos: 'Preparando dados...', 'Fazendo upload das imagens...', 'Ajustando preços...', 'Finalizando...'.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  // === Produto Inline + Lote ===
  {
    id: "inline-existing-modal",
    category: "inline-lote",
    title: "Scan de código que já existe — modal aparece",
    howToTest: "Na página de criar produto (dentro da movimentação), escaneie um código de barras de um produto que já existe. Deve aparecer um modal 'Produto já existe' com as opções 'Cancelar' e 'Adicionar Lote'.",
    pageUrl: "/stock-movements/create/new-product",
    pageLabel: "Novo Produto (inline)",
  },
  {
    id: "inline-existing-cancel",
    category: "inline-lote",
    title: "Cancelar modal de produto existente",
    howToTest: "No modal 'Produto já existe', clique em 'Cancelar'. O modal deve fechar e o formulário deve continuar como estava.",
    pageUrl: "/stock-movements/create/new-product",
    pageLabel: "Novo Produto (inline)",
  },
  {
    id: "inline-existing-add-batch",
    category: "inline-lote",
    title: "Adicionar lote ao produto existente",
    howToTest: "No modal 'Produto já existe', clique em 'Adicionar Lote'. Preencha quantidade, datas e preços. Confirme. O item deve aparecer na lista da movimentação.",
    pageUrl: "/stock-movements/create/new-product",
    pageLabel: "Novo Produto (inline)",
  },
  {
    id: "inline-price-suggestion",
    category: "inline-lote",
    title: "Sugestão de preço do último lote",
    howToTest: "Ao adicionar um lote para um produto que já tem histórico, os campos de preço de custo e venda devem vir preenchidos com os valores do último lote.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  {
    id: "inline-duplicate-name",
    category: "inline-lote",
    title: "Produto inline duplicado (mesmo nome)",
    howToTest: "Adicione um produto inline chamado 'Produto A'. Tente adicionar outro produto inline também chamado 'Produto A'. Deve mostrar erro de duplicata.",
    pageUrl: "/stock-movements/create/new-product",
    pageLabel: "Novo Produto (inline)",
  },
  {
    id: "inline-duplicate-barcode",
    category: "inline-lote",
    title: "Produto inline duplicado (mesmo código)",
    howToTest: "Adicione um produto inline com código '123'. Tente adicionar outro produto inline com o mesmo código '123'. Deve mostrar erro de conflito.",
    pageUrl: "/stock-movements/create/new-product",
    pageLabel: "Novo Produto (inline)",
  },
  {
    id: "inline-existing-barcode-conflict",
    category: "inline-lote",
    title: "Inline + produto existente com mesmo código",
    howToTest: "Adicione um produto inline com código 'ABC'. Depois use o scanner para ler um produto existente que tem o código 'ABC'. Deve mostrar aviso de conflito e bloquear.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  // === Transferências ===
  {
    id: "transfer-full-flow",
    category: "transferencias",
    title: "Fluxo completo de transferência",
    howToTest: "Vá para a página de nova transferência. Selecione o armazém de origem e destino. Busque um produto. Selecione um lote. Ajuste a quantidade. Confirme. Envie a transferência.",
    pageUrl: "/transfers/new",
    pageLabel: "Nova Transferência",
  },
  {
    id: "transfer-scanner",
    category: "transferencias",
    title: "Scanner na transferência",
    howToTest: "Na página de nova transferência, clique no ícone de scanner. Escaneie um produto. O produto deve ser encontrado e o drawer de lote deve abrir.",
    pageUrl: "/transfers/new",
    pageLabel: "Nova Transferência",
  },
  {
    id: "transfer-no-batches",
    category: "transferencias",
    title: "Produto sem lotes disponíveis",
    howToTest: "Na transferência, busque um produto que não tenha lotes cadastrados. O drawer de lote deve aparecer vazio.",
    pageUrl: "/transfers/new",
    pageLabel: "Nova Transferência",
  },
  {
    id: "transfer-same-warehouse",
    category: "transferencias",
    title: "Mesmo armazém origem e destino",
    howToTest: "Tente selecionar o mesmo armazém como origem e destino. O sistema deve bloquear essa ação.",
    pageUrl: "/transfers/new",
    pageLabel: "Nova Transferência",
  },
  {
    id: "transfer-multiple-items",
    category: "transferencias",
    title: "Múltiplos itens na transferência",
    howToTest: "Adicione 5 ou mais itens diferentes. Verifique se a lista mostra todos corretamente (cards no celular, tabela no desktop).",
    pageUrl: "/transfers/new",
    pageLabel: "Nova Transferência",
  },
  {
    id: "transfer-remove-item",
    category: "transferencias",
    title: "Remover item da lista",
    howToTest: "Adicione um item. Clique no botão de remover (ícone de lixeira). O item deve sumir da lista imediatamente.",
    pageUrl: "/transfers/new",
    pageLabel: "Nova Transferência",
  },
  // === Prompts ===
  {
    id: "prompts-create",
    category: "prompts",
    title: "Criar um prompt",
    howToTest: "Na página de detalhes do produto, clique na aba 'Prompts'. Clique em 'Criar prompt'. Faça upload de uma imagem de fundo. Dê um nome. Salve.",
    pageUrl: "/products",
    pageLabel: "Lista de Produtos",
  },
  {
    id: "prompts-generate-auto-price",
    category: "prompts",
    title: "Gerar com preço automático do lote",
    howToTest: "Abra um prompt de um produto que tenha lotes. O campo de preço deve vir preenchido automaticamente com o valor do último lote.",
    pageUrl: "/products",
    pageLabel: "Lista de Produtos",
  },
  {
    id: "prompts-generate-manual-price",
    category: "prompts",
    title: "Gerar com preço manual",
    howToTest: "No prompt, altere o preço manualmente para um valor diferente do sugerido. Clique em 'Gerar'. O sistema deve usar o valor que você digitou.",
    pageUrl: "/products",
    pageLabel: "Lista de Produtos",
  },
  {
    id: "prompts-cash-offer",
    category: "prompts",
    title: "Opção de oferta à vista",
    howToTest: "Na página de gerar prompt, ative 'Oferta à vista'. Escolha entre 'Preço final' ou '% de desconto'. O preço à vista deve ser calculado.",
    pageUrl: "/products",
    pageLabel: "Lista de Produtos",
  },
  {
    id: "prompts-installments",
    category: "prompts",
    title: "Parcelamento",
    howToTest: "Na página de gerar prompt, ative o parcelamento. Defina o número de parcelas. O valor da parcela deve ser calculado automaticamente.",
    pageUrl: "/products",
    pageLabel: "Lista de Produtos",
  },
  {
    id: "prompts-share-android",
    category: "prompts",
    title: "Compartilhar no Android/Desktop",
    howToTest: "Gere um prompt e clique em 'Gerar imagem'. Deve abrir a janela de compartilhamento nativa do sistema.",
    pageUrl: "/products",
    pageLabel: "Lista de Produtos",
  },
  {
    id: "prompts-share-ios-pwa",
    category: "prompts",
    title: "Compartilhar no iOS PWA",
    howToTest: "Abra o app como PWA no iPhone. Gere um prompt. O sistema deve mostrar uma mensagem informando que o compartilhamento de arquivos é bloqueado no iOS PWA.",
    pageUrl: "/products",
    pageLabel: "Lista de Produtos",
  },
  {
    id: "prompts-cancel-share",
    category: "prompts",
    title: "Cancelar compartilhamento",
    howToTest: "Gere um prompt. Quando a janela de compartilhar abrir, cancele. O app deve voltar para a lista de prompts.",
    pageUrl: "/products",
    pageLabel: "Lista de Produtos",
  },
  {
    id: "prompts-no-logo",
    category: "prompts",
    title: "Empresa sem logo",
    howToTest: "Gere um prompt para uma empresa que não tem logo cadastrada. A imagem deve ser gerada sem o logo (sem quebrar).",
    pageUrl: "/products",
    pageLabel: "Lista de Produtos",
  },
  {
    id: "prompts-double-click",
    category: "prompts",
    title: "Clique rápido em Gerar",
    howToTest: "Na página de gerar prompt, clique duas vezes bem rápido no botão 'Gerar imagem'. O sistema deve bloquear o segundo clique.",
    pageUrl: "/products",
    pageLabel: "Lista de Produtos",
  },
  // === Formulário de Produto ===
  {
    id: "produto-form-large-image",
    category: "produto-form",
    title: "Upload de imagem muito grande (acima de 5MB)",
    howToTest: "Na página de criar/editar produto, tente fazer upload de uma imagem com mais de 5MB. O sistema deve rejeitar.",
    pageUrl: "/products/create",
    pageLabel: "Criar Produto",
  },
  {
    id: "produto-form-processing-lock",
    category: "produto-form",
    title: "Lock de processamento de imagem",
    howToTest: "Faça upload de uma imagem válida. Enquanto a imagem estiver processando, o botão de salvar deve ficar desabilitado e mostrar 'Imagem...' com um spinner.",
    pageUrl: "/products/create",
    pageLabel: "Criar Produto",
  },
  {
    id: "produto-form-submit-processing",
    category: "produto-form",
    title: "Tentar salvar durante processamento",
    howToTest: "Faça upload de uma imagem e imediatamente tente clicar em salvar. Deve aparecer um toast avisando: 'Aguarde a imagem terminar de processar antes de salvar.'",
    pageUrl: "/products/create",
    pageLabel: "Criar Produto",
  },
  {
    id: "produto-form-continuous",
    category: "produto-form",
    title: "Produto inline contínuo",
    howToTest: "Ao criar um produto inline dentro de uma movimentação, após salvar o formulário deve resetar e permanecer na mesma página para adicionar outro.",
    pageUrl: "/stock-movements/create/new-product",
    pageLabel: "Novo Produto (inline)",
  },
  // === API ===
  {
    id: "api-token-expired",
    category: "api",
    title: "Token expirado durante uso",
    howToTest: "Mantenha a sessão aberta por várias horas (ou use ferramentas de desenvolvimento para simular). Quando o token expirar, a próxima requisição deve renovar automaticamente sem redirecionar para o login.",
    pageUrl: "/stock-movements",
    pageLabel: "Movimentações",
  },
  {
    id: "api-multiple-401",
    category: "api",
    title: "Múltiplas chamadas com token expirado",
    howToTest: "Carregue uma página com várias requisições ao mesmo tempo (ex: dashboard). Se o token estiver expirado, apenas uma renovação deve ocorrer e todas as chamadas devem ser repetidas.",
    pageUrl: "/stock-movements",
    pageLabel: "Movimentações",
  },
  {
    id: "api-refresh-fails",
    category: "api",
    title: "Refresh de token falha",
    howToTest: "Simule um token inválido (logout em outra aba). A aplicação deve redirecionar para a página de login.",
    pageUrl: "/stock-movements",
    pageLabel: "Movimentações",
  },
  {
    id: "api-403-forbidden",
    category: "api",
    title: "Erro 403 sem tentar refresh",
    howToTest: "Tente acessar um recurso que você não tem permissão. O sistema deve mostrar o erro 403 diretamente, sem tentar renovar o token.",
    pageUrl: "/system",
    pageLabel: "Sistema",
  },
  // === Toasts ===
  {
    id: "toasts-style",
    category: "toasts",
    title: "Aparência dos toasts no tema brutalista",
    howToTest: "Disparar qualquer toast (ex: salvar um produto, erro de validação). Verifique se o fundo é escuro (#171717), borda cinza, texto claro (#FAFAFA), bordas retas (4px).",
    pageUrl: "/products/create",
    pageLabel: "Criar Produto",
  },
  {
    id: "toasts-position",
    category: "toasts",
    title: "Posição dos toasts",
    howToTest: "Disparar qualquer toast. Ele deve aparecer no topo central da tela.",
    pageUrl: "/products/create",
    pageLabel: "Criar Produto",
  },
  {
    id: "toasts-language",
    category: "toasts",
    title: "Mensagens em português",
    howToTest: "Cause diferentes ações que gerem toasts (salvar, erro, validação). Todas as mensagens devem estar em português do Brasil.",
    pageUrl: "/products/create",
    pageLabel: "Criar Produto",
  },
  {
    id: "toasts-long-text",
    category: "toasts",
    title: "Toast com texto longo",
    howToTest: "Se encontrar um toast com mensagem longa, verifique se o texto não quebra o layout nem corta palavras.",
    pageUrl: "/stock-movements/create",
    pageLabel: "Nova Movimentação",
  },
  {
    id: "toasts-stacking",
    category: "toasts",
    title: "Empilhamento de múltiplos toasts",
    howToTest: "Disparar 3 toasts em sequência rápida. Eles devem empilhar um abaixo do outro sem se sobrepor.",
    pageUrl: "/products/create",
    pageLabel: "Criar Produto",
  },
  // === Warehouse ===
  {
    id: "warehouse-instant-load",
    category: "warehouse",
    title: "Warehouse carrega instantaneamente",
    howToTest: "Com um warehouse já selecionado, recarregue a página (F5). O nome do warehouse deve aparecer imediatamente no topo, sem flicker ou atraso.",
    pageUrl: "/products",
    pageLabel: "Produtos",
  },
  {
    id: "warehouse-no-selection",
    category: "warehouse",
    title: "Primeiro acesso (sem warehouse)",
    howToTest: "Limpe o armazenamento local (localStorage) do navegador. Acesse o app. Nenhum warehouse deve estar selecionado e as páginas devem lidar com isso.",
    pageUrl: "/products",
    pageLabel: "Produtos",
  },
  {
    id: "warehouse-stable-navigation",
    category: "warehouse",
    title: "Warehouse estável na navegação",
    howToTest: "Selecione um warehouse. Navegue entre 3 ou 4 páginas diferentes (Produtos, Vendas, Movimentações). O warehouse selecionado deve permanecer o mesmo.",
    pageUrl: "/products",
    pageLabel: "Produtos",
  },
];
